namespace Raiden.Data;

public sealed class Solution
{
    private const string CONFIG_NAME = ".raidenconfig";
    private const string OBJDIR_NAME = ".raiden";

    public Solution(string source)
    {
        Source = new(source);
        Object = Source.Combine(OBJDIR_NAME);
        Config = Source.CombineToFile(CONFIG_NAME);

        if (!Source.Exists)
        {
            Source.Create();
        }

        if (!Object.Exists && Config.Exists)
        {
            Object.Create();
            Object.Attributes = FileAttributes.Directory | FileAttributes.Hidden;
        }
    }

    public FileInfo Config
    {
        get;
        init;
    }

    public bool HasConfiguration => Config.Exists;

    /// <summary>
    /// The object directory where all the metadata used or/and generated by Raiden are stored.
    /// </summary>
    public DirectoryInfo Object
    {
        get;
        init;
    }

    public DirectoryInfo Source
    {
        get;
        init;
    }

    public Configuration GetConfiguration()
    {
        if (!HasConfiguration)
        {
            Cli.WriteError(
                "Solution has no configuration file."
            );
        }

        return Configuration.Read(Config.FullName);
    }

    public static void CopyContent(string src,
                               string dst,
                               bool overwrite = false)
    {
        if (!File.Exists(src))
        {
            throw new FileNotFoundException(src);
        }

        if (!File.Exists(dst) || overwrite)
        {
            var content = File.ReadAllText(src);
            File.WriteAllText(dst, content);
        }
    }

    /// <summary>
    /// Content isn't overwritten if it exists.
    /// </summary>
    public static void Save(string path, string content)
        => Save(path, content, false);

    /// <remarks>
    /// Overwrites the content if it exists.
    /// </remarks>
    public static void SaveUnsafe(string path, string content)
        => Save(path, content, true);

    private static void Save(string path,
                             string content,
                             bool overwrite)
    {
        if (!File.Exists(path) || overwrite)
        {
            File.WriteAllText(path, content);
        }
    }
}